### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by DynWebService** [freshworkstudio/gps-tracking-nodejs#12]
Hello,

I recently implemented an adapter for a device, but eventually the node stops the error below:
`
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1020:11)
    at TCP.onread (net.js:568:26)
`

Can you help me?

**Comment by vcianaya** [comment]
Hello, I have the same problem, did you solve it ???

**Comment by maykonmultilig** [comment]
Hello,

Yes, i just add the follow lines in my server.js:
```
    connection.on('error', function (data) {
       //error handling here 
    })
```
in my case i just ignore this.
```
connection.on('error', function (data) {
        console.log("Connection Error: ");
        console.log(data);
       // device.error(data, 'Connection error');
    });
```


my server.js
```
var server = gps.server(options,function(device, connection){

    device.on("login_request",function(device_id, msg_parts){
        if (device_id < 0) {
            this.login_authorized(false);
        } else {
            this.login_authorized(true);
        }

    });

    //PING -> When the gps sends their position  
    device.on("ping",function(data){
        return data;
    });

    connection.on('error', function (data) {
        console.log("Connection Error: ");
        console.log(data);
       // device.error(data, 'Connection error');
    });

});

```

**Comment by gonzunigad** [comment]
Do you have some code example so I can test the problem?

**Comment by vcianaya** [comment]
![image](https://user-images.githubusercontent.com/14941815/39944002-e6574f10-5532-11e8-9e66-663cdcdaf416.png)

**Comment by GokulanJayaram** [comment]
What is the best way to resolve this than just ignoring?
